"""posts table date column is changed.

Revision ID: 0cee68eb4ef3
Revises: 5e675a9b8a2a
Create Date: 2023-01-12 20:47:13.935931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cee68eb4ef3'
down_revision = '5e675a9b8a2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
