"""empty message

Revision ID: 48e0d370efe9
Revises: 54f512737630
Create Date: 2023-01-13 22:36:39.444179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e0d370efe9'
down_revision = '54f512737630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('dislikes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes_count')
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###
