"""dislikes\likes counts added.

Revision ID: 51239e3cbd09
Revises: 48e0d370efe9
Create Date: 2023-01-13 22:38:14.188139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51239e3cbd09'
down_revision = '48e0d370efe9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
