"""posts table date column is changed.

Revision ID: 5e675a9b8a2a
Revises: 23c32eacc31a
Create Date: 2023-01-12 20:46:39.948744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e675a9b8a2a'
down_revision = '23c32eacc31a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
