"""dislikes\likes counts added.

Revision ID: feebe63ce03c
Revises: 51239e3cbd09
Create Date: 2023-01-13 22:39:39.941027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feebe63ce03c'
down_revision = '51239e3cbd09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
